repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      #   - id: check-yaml # does not work with CloudFormation short form
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: requirements-txt-fixer
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint
      - id: shellcheck
      - id: shfmt
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: tfupdate
      - id: terraform_fmt
      - id: terraform_tflint
      # - id: terraform_tfsec TODO
      - id: terraform_docs
      # - id: terraform_validate TODO
